version: "3.4"

services:
  frontend:
    build: .
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    stdin_open: true
    environment:
      - NODE_ENV=development
    command: npm start